apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
        - name: fetcher
          image: fetcher:latest
          command: ["bot", "once"]
---
apiVersion: v1
kind: Service
metadata:
  name: fetcher
spec:
  selector:
    app: fetcher
  ports:
    - port: 80
      targetPort: 80
